// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKrLforSwpUWvQlyl0wsyiGjyZL-HUGEw',
    appId: '1:979235485242:web:a5252ae089585b13676703',
    messagingSenderId: '979235485242',
    projectId: 'local-skill-share-e06d4',
    authDomain: 'local-skill-share-e06d4.firebaseapp.com',
    storageBucket: 'local-skill-share-e06d4.firebasestorage.app',
    measurementId: 'G-VGM6W8NRQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sVAcJoCqAnHnsLaPeNfWEdGcyzkLZAY',
    appId: '1:979235485242:android:0ff8ee546df1d866676703',
    messagingSenderId: '979235485242',
    projectId: 'local-skill-share-e06d4',
    storageBucket: 'local-skill-share-e06d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTCyRQUPkzzRBw1vhrcNKpFUxV8-xhmM',
    appId: '1:979235485242:ios:69e5d46790c5dd88676703',
    messagingSenderId: '979235485242',
    projectId: 'local-skill-share-e06d4',
    storageBucket: 'local-skill-share-e06d4.firebasestorage.app',
    iosBundleId: 'com.example.localSkillShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTCyRQUPkzzRBw1vhrcNKpFUxV8-xhmM',
    appId: '1:979235485242:ios:69e5d46790c5dd88676703',
    messagingSenderId: '979235485242',
    projectId: 'local-skill-share-e06d4',
    storageBucket: 'local-skill-share-e06d4.firebasestorage.app',
    iosBundleId: 'com.example.localSkillShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKrLforSwpUWvQlyl0wsyiGjyZL-HUGEw',
    appId: '1:979235485242:web:81f28843432b1ff0676703',
    messagingSenderId: '979235485242',
    projectId: 'local-skill-share-e06d4',
    authDomain: 'local-skill-share-e06d4.firebaseapp.com',
    storageBucket: 'local-skill-share-e06d4.firebasestorage.app',
    measurementId: 'G-H9QE6VK6KL',
  );
}
